import { Session } from "@/types";

export const mockSessions: Session[] = [
  {
    id: "1",
    sessionId: "SID-00042137",
    candidateName: "Aiden Clarke",
    candidateEmail: "aiden.clarke@example.com",
    examTitle: "Software Engineering L3",
    status: "Active",
    riskScore: 34,
    riskLevel: "Medium",
    duration: "1h 24m",
    lastActivity: "2m ago",
    warningCount: 2,
    startTime: "07:30:00 AM",
    timeline: [
      { id: "e1", timestamp: "07:30:00 AM", date: "May 24, 2026", eventType: "session_started", severity: "success", description: "Session initialized and verified" },
      { id: "e2", timestamp: "07:52:14 AM", date: "May 24, 2026", eventType: "tab_switch", severity: "warning", description: "Candidate switched to external tab" },
      { id: "e3", timestamp: "08:14:22 AM", date: "May 24, 2026", eventType: "focus_loss", severity: "warning", description: "Application focus lost for 3.2s" },
    ],
  },
  {
    id: "2",
    sessionId: "SID-00050056",
    candidateName: "Priya Nair",
    candidateEmail: "priya.nair@example.com",
    examTitle: "Frontend Development Test",
    status: "Flagged",
    riskScore: 86,
    riskLevel: "Critical",
    duration: "2h 10m",
    lastActivity: "5m ago",
    warningCount: 5,
    startTime: "07:30:00 AM",
    timeline: [
      { id: "e1", timestamp: "07:30:00 AM", date: "May 24, 2026", eventType: "session_started", severity: "success", description: "Session initialized and verified" },
      { id: "e2", timestamp: "07:45:12 AM", date: "May 24, 2026", eventType: "tab_switch", severity: "warning", description: "Candidate switched to external tab" },
      { id: "e3", timestamp: "08:02:31 AM", date: "May 24, 2026", eventType: "fullscreen_exit", severity: "warning", description: "Fullscreen mode exited" },
      { id: "e4", timestamp: "08:15:44 AM", date: "May 24, 2026", eventType: "focus_loss", severity: "warning", description: "Application focus lost for 4.2s" },
      { id: "e5", timestamp: "08:32:18 AM", date: "May 24, 2026", eventType: "inactivity_warning", severity: "warning", description: "No input detected for 90 seconds" },
      { id: "e6", timestamp: "08:55:02 AM", date: "May 24, 2026", eventType: "network_interruption", severity: "critical", description: "Network connection dropped for 8s" },
      { id: "e7", timestamp: "08:55:12 AM", date: "May 24, 2026", eventType: "reconnect", severity: "info", description: "Session reconnected successfully" },
    ],
  },
  {
    id: "3",
    sessionId: "SID-00057891",
    candidateName: "Marcus Webb",
    candidateEmail: "marcus.webb@example.com",
    examTitle: "Data Structures & Algorithms",
    status: "Completed",
    riskScore: 18,
    riskLevel: "Low",
    duration: "1h 45m",
    lastActivity: "12m ago",
    warningCount: 0,
    startTime: "09:00:00 AM",
    timeline: [
      { id: "e1", timestamp: "09:00:00 AM", date: "May 24, 2026", eventType: "session_started", severity: "success", description: "Session initialized and verified" },
    ],
  },
  {
    id: "4",
    sessionId: "SID-00065234",
    candidateName: "Sofia Almeida",
    candidateEmail: "sofia.almeida@example.com",
    examTitle: "System Design Assessment",
    status: "Reviewing",
    riskScore: 61,
    riskLevel: "High",
    duration: "58m",
    lastActivity: "1m ago",
    warningCount: 3,
    startTime: "10:15:00 AM",
    timeline: [
      { id: "e1", timestamp: "10:15:00 AM", date: "May 24, 2026", eventType: "session_started", severity: "success", description: "Session initialized and verified" },
      { id: "e2", timestamp: "10:34:22 AM", date: "May 24, 2026", eventType: "tab_switch", severity: "warning", description: "Candidate switched to external tab" },
      { id: "e3", timestamp: "10:52:11 AM", date: "May 24, 2026", eventType: "network_interruption", severity: "critical", description: "Network connection dropped for 12s" },
      { id: "e4", timestamp: "10:52:25 AM", date: "May 24, 2026", eventType: "reconnect", severity: "info", description: "Session reconnected successfully" },
    ],
  },
  {
    id: "5",
    sessionId: "SID-00073112",
    candidateName: "James Okafor",
    candidateEmail: "james.okafor@example.com",
    examTitle: "Cloud Architecture Review",
    status: "Suspended",
    riskScore: 94,
    riskLevel: "Critical",
    duration: "1h 12m",
    lastActivity: "9m ago",
    warningCount: 7,
    startTime: "08:00:00 AM",
    timeline: [
      { id: "e1", timestamp: "08:00:00 AM", date: "May 24, 2026", eventType: "session_started", severity: "success", description: "Session initialized and verified" },
      { id: "e2", timestamp: "08:12:05 AM", date: "May 24, 2026", eventType: "fullscreen_exit", severity: "warning", description: "Fullscreen mode exited" },
      { id: "e3", timestamp: "08:24:18 AM", date: "May 24, 2026", eventType: "tab_switch", severity: "warning", description: "Candidate switched to external tab" },
      { id: "e4", timestamp: "08:36:44 AM", date: "May 24, 2026", eventType: "focus_loss", severity: "warning", description: "Application focus lost for 8.1s" },
      { id: "e5", timestamp: "08:48:02 AM", date: "May 24, 2026", eventType: "inactivity_warning", severity: "warning", description: "No input detected for 120 seconds" },
      { id: "e6", timestamp: "09:01:15 AM", date: "May 24, 2026", eventType: "network_interruption", severity: "critical", description: "Network connection dropped for 25s" },
      { id: "e7", timestamp: "09:02:00 AM", date: "May 24, 2026", eventType: "reconnect", severity: "info", description: "Session reconnected successfully" },
    ],
  },
  {
    id: "6",
    sessionId: "SID-00081245",
    candidateName: "Yuna Kim",
    candidateEmail: "yuna.kim@example.com",
    examTitle: "Behavioral Assessment",
    status: "Active",
    riskScore: 22,
    riskLevel: "Low",
    duration: "43m",
    lastActivity: "Just now",
    warningCount: 1,
    startTime: "11:00:00 AM",
    timeline: [
      { id: "e1", timestamp: "11:00:00 AM", date: "May 24, 2026", eventType: "session_started", severity: "success", description: "Session initialized and verified" },
      { id: "e2", timestamp: "11:22:33 AM", date: "May 24, 2026", eventType: "inactivity_warning", severity: "warning", description: "No input detected for 60 seconds" },
    ],
  },
  {
    id: "7",
    sessionId: "SID-00088921",
    candidateName: "Luca Ferrari",
    candidateEmail: "luca.ferrari@example.com",
    examTitle: "Python Proficiency Exam",
    status: "Completed",
    riskScore: 11,
    riskLevel: "Low",
    duration: "2h 02m",
    lastActivity: "15m ago",
    warningCount: 0,
    startTime: "08:30:00 AM",
    timeline: [
      { id: "e1", timestamp: "08:30:00 AM", date: "May 24, 2026", eventType: "session_started", severity: "success", description: "Session initialized and verified" },
    ],
  },
  {
    id: "8",
    sessionId: "SID-00094567",
    candidateName: "Amara Diallo",
    candidateEmail: "amara.diallo@example.com",
    examTitle: "Machine Learning Fundamentals",
    status: "Flagged",
    riskScore: 78,
    riskLevel: "High",
    duration: "1h 31m",
    lastActivity: "4m ago",
    warningCount: 4,
    startTime: "09:30:00 AM",
    timeline: [
      { id: "e1", timestamp: "09:30:00 AM", date: "May 24, 2026", eventType: "session_started", severity: "success", description: "Session initialized and verified" },
      { id: "e2", timestamp: "09:48:14 AM", date: "May 24, 2026", eventType: "tab_switch", severity: "warning", description: "Candidate switched to external tab" },
      { id: "e3", timestamp: "10:05:22 AM", date: "May 24, 2026", eventType: "fullscreen_exit", severity: "warning", description: "Fullscreen mode exited" },
      { id: "e4", timestamp: "10:22:41 AM", date: "May 24, 2026", eventType: "focus_loss", severity: "warning", description: "Application focus lost for 6.8s" },
      { id: "e5", timestamp: "10:44:03 AM", date: "May 24, 2026", eventType: "network_interruption", severity: "critical", description: "Network connection dropped for 5s" },
    ],
  },
  {
    id: "9",
    sessionId: "SID-00102318",
    candidateName: "Noah Fischer",
    candidateEmail: "noah.fischer@example.com",
    examTitle: "Frontend Development Test",
    status: "Reviewing",
    riskScore: 55,
    riskLevel: "High",
    duration: "1h 08m",
    lastActivity: "3m ago",
    warningCount: 2,
    startTime: "10:00:00 AM",
    timeline: [
      { id: "e1", timestamp: "10:00:00 AM", date: "May 24, 2026", eventType: "session_started", severity: "success", description: "Session initialized and verified" },
      { id: "e2", timestamp: "10:18:55 AM", date: "May 24, 2026", eventType: "tab_switch", severity: "warning", description: "Candidate switched to external tab" },
      { id: "e3", timestamp: "10:42:17 AM", date: "May 24, 2026", eventType: "inactivity_warning", severity: "warning", description: "No input detected for 75 seconds" },
    ],
  },
  {
    id: "10",
    sessionId: "SID-00110992",
    candidateName: "Isabella Vargas",
    candidateEmail: "isabella.vargas@example.com",
    examTitle: "System Design Assessment",
    status: "Active",
    riskScore: 27,
    riskLevel: "Medium",
    duration: "52m",
    lastActivity: "1m ago",
    warningCount: 1,
    startTime: "11:10:00 AM",
    timeline: [
      { id: "e1", timestamp: "11:10:00 AM", date: "May 24, 2026", eventType: "session_started", severity: "success", description: "Session initialized and verified" },
      { id: "e2", timestamp: "11:34:09 AM", date: "May 24, 2026", eventType: "fullscreen_exit", severity: "warning", description: "Fullscreen mode exited" },
    ],
  },
  {
    id: "11",
    sessionId: "SID-00118445",
    candidateName: "Chen Wei",
    candidateEmail: "chen.wei@example.com",
    examTitle: "DevOps Certification",
    status: "Active",
    riskScore: 19,
    riskLevel: "Low",
    duration: "38m",
    lastActivity: "Just now",
    warningCount: 0,
    startTime: "11:25:00 AM",
    timeline: [
      { id: "e1", timestamp: "11:25:00 AM", date: "May 24, 2026", eventType: "session_started", severity: "success", description: "Session initialized and verified" },
    ],
  },
  {
    id: "12",
    sessionId: "SID-00126780",
    candidateName: "Elena Petrova",
    candidateEmail: "elena.petrova@example.com",
    examTitle: "Database Administration",
    status: "Reviewing",
    riskScore: 48,
    riskLevel: "Medium",
    duration: "1h 15m",
    lastActivity: "6m ago",
    warningCount: 2,
    startTime: "09:45:00 AM",
    timeline: [
      { id: "e1", timestamp: "09:45:00 AM", date: "May 24, 2026", eventType: "session_started", severity: "success", description: "Session initialized and verified" },
      { id: "e2", timestamp: "10:08:33 AM", date: "May 24, 2026", eventType: "focus_loss", severity: "warning", description: "Application focus lost for 2.9s" },
      { id: "e3", timestamp: "10:41:22 AM", date: "May 24, 2026", eventType: "tab_switch", severity: "warning", description: "Candidate switched to external tab" },
    ],
  },
  {
    id: "13",
    sessionId: "SID-00135012",
    candidateName: "Omar Hassan",
    candidateEmail: "omar.hassan@example.com",
    examTitle: "Cybersecurity Fundamentals",
    status: "Flagged",
    riskScore: 72,
    riskLevel: "High",
    duration: "1h 48m",
    lastActivity: "8m ago",
    warningCount: 4,
    startTime: "08:45:00 AM",
    timeline: [
      { id: "e1", timestamp: "08:45:00 AM", date: "May 24, 2026", eventType: "session_started", severity: "success", description: "Session initialized and verified" },
      { id: "e2", timestamp: "09:02:17 AM", date: "May 24, 2026", eventType: "tab_switch", severity: "warning", description: "Candidate switched to external tab" },
      { id: "e3", timestamp: "09:28:44 AM", date: "May 24, 2026", eventType: "fullscreen_exit", severity: "warning", description: "Fullscreen mode exited" },
      { id: "e4", timestamp: "09:55:30 AM", date: "May 24, 2026", eventType: "network_interruption", severity: "critical", description: "Network connection dropped for 15s" },
      { id: "e5", timestamp: "09:55:48 AM", date: "May 24, 2026", eventType: "reconnect", severity: "info", description: "Session reconnected successfully" },
    ],
  },
  {
    id: "14",
    sessionId: "SID-00143256",
    candidateName: "Mei Lin",
    candidateEmail: "mei.lin@example.com",
    examTitle: "React Developer Assessment",
    status: "Completed",
    riskScore: 8,
    riskLevel: "Low",
    duration: "1h 55m",
    lastActivity: "22m ago",
    warningCount: 0,
    startTime: "08:00:00 AM",
    timeline: [
      { id: "e1", timestamp: "08:00:00 AM", date: "May 24, 2026", eventType: "session_started", severity: "success", description: "Session initialized and verified" },
    ],
  },
  {
    id: "15",
    sessionId: "SID-00151489",
    candidateName: "Raj Patel",
    candidateEmail: "raj.patel@example.com",
    examTitle: "Cloud Architecture Review",
    status: "Active",
    riskScore: 31,
    riskLevel: "Medium",
    duration: "1h 02m",
    lastActivity: "2m ago",
    warningCount: 1,
    startTime: "10:30:00 AM",
    timeline: [
      { id: "e1", timestamp: "10:30:00 AM", date: "May 24, 2026", eventType: "session_started", severity: "success", description: "Session initialized and verified" },
      { id: "e2", timestamp: "11:04:18 AM", date: "May 24, 2026", eventType: "inactivity_warning", severity: "warning", description: "No input detected for 80 seconds" },
    ],
  },
  {
    id: "16",
    sessionId: "SID-00159722",
    candidateName: "Sara Johnson",
    candidateEmail: "sara.johnson@example.com",
    examTitle: "Python Proficiency Exam",
    status: "Suspended",
    riskScore: 91,
    riskLevel: "Critical",
    duration: "44m",
    lastActivity: "18m ago",
    warningCount: 6,
    startTime: "09:15:00 AM",
    timeline: [
      { id: "e1", timestamp: "09:15:00 AM", date: "May 24, 2026", eventType: "session_started", severity: "success", description: "Session initialized and verified" },
      { id: "e2", timestamp: "09:22:05 AM", date: "May 24, 2026", eventType: "tab_switch", severity: "warning", description: "Candidate switched to external tab" },
      { id: "e3", timestamp: "09:29:14 AM", date: "May 24, 2026", eventType: "fullscreen_exit", severity: "warning", description: "Fullscreen mode exited" },
      { id: "e4", timestamp: "09:35:22 AM", date: "May 24, 2026", eventType: "focus_loss", severity: "warning", description: "Application focus lost for 12s" },
      { id: "e5", timestamp: "09:41:33 AM", date: "May 24, 2026", eventType: "tab_switch", severity: "warning", description: "Candidate switched to external tab" },
      { id: "e6", timestamp: "09:48:01 AM", date: "May 24, 2026", eventType: "network_interruption", severity: "critical", description: "Network connection dropped for 20s" },
      { id: "e7", timestamp: "09:58:15 AM", date: "May 24, 2026", eventType: "inactivity_warning", severity: "warning", description: "No input detected for 150 seconds" },
    ],
  },
  {
    id: "17",
    sessionId: "SID-00167955",
    candidateName: "Andre Rousseau",
    candidateEmail: "andre.rousseau@example.com",
    examTitle: "Data Science Evaluation",
    status: "Completed",
    riskScore: 24,
    riskLevel: "Low",
    duration: "2h 18m",
    lastActivity: "30m ago",
    warningCount: 1,
    startTime: "07:45:00 AM",
    timeline: [
      { id: "e1", timestamp: "07:45:00 AM", date: "May 24, 2026", eventType: "session_started", severity: "success", description: "Session initialized and verified" },
      { id: "e2", timestamp: "08:52:44 AM", date: "May 24, 2026", eventType: "tab_switch", severity: "warning", description: "Candidate switched to external tab" },
    ],
  },
  {
    id: "18",
    sessionId: "SID-00176188",
    candidateName: "Fatima Al-Rashid",
    candidateEmail: "fatima.alrashid@example.com",
    examTitle: "Machine Learning Fundamentals",
    status: "Reviewing",
    riskScore: 58,
    riskLevel: "High",
    duration: "1h 22m",
    lastActivity: "5m ago",
    warningCount: 3,
    startTime: "09:50:00 AM",
    timeline: [
      { id: "e1", timestamp: "09:50:00 AM", date: "May 24, 2026", eventType: "session_started", severity: "success", description: "Session initialized and verified" },
      { id: "e2", timestamp: "10:12:19 AM", date: "May 24, 2026", eventType: "focus_loss", severity: "warning", description: "Application focus lost for 5.5s" },
      { id: "e3", timestamp: "10:38:44 AM", date: "May 24, 2026", eventType: "network_interruption", severity: "critical", description: "Network connection dropped for 7s" },
      { id: "e4", timestamp: "10:38:53 AM", date: "May 24, 2026", eventType: "reconnect", severity: "info", description: "Session reconnected successfully" },
    ],
  },
  {
    id: "19",
    sessionId: "SID-00184421",
    candidateName: "Ethan Brooks",
    candidateEmail: "ethan.brooks@example.com",
    examTitle: "Software Engineering L3",
    status: "Active",
    riskScore: 16,
    riskLevel: "Low",
    duration: "29m",
    lastActivity: "Just now",
    warningCount: 0,
    startTime: "11:35:00 AM",
    timeline: [
      { id: "e1", timestamp: "11:35:00 AM", date: "May 24, 2026", eventType: "session_started", severity: "success", description: "Session initialized and verified" },
    ],
  },
  {
    id: "20",
    sessionId: "SID-00192654",
    candidateName: "Layla Mansour",
    candidateEmail: "layla.mansour@example.com",
    examTitle: "Behavioral Assessment",
    status: "Flagged",
    riskScore: 83,
    riskLevel: "Critical",
    duration: "1h 40m",
    lastActivity: "7m ago",
    warningCount: 5,
    startTime: "09:00:00 AM",
    timeline: [
      { id: "e1", timestamp: "09:00:00 AM", date: "May 24, 2026", eventType: "session_started", severity: "success", description: "Session initialized and verified" },
      { id: "e2", timestamp: "09:18:22 AM", date: "May 24, 2026", eventType: "tab_switch", severity: "warning", description: "Candidate switched to external tab" },
      { id: "e3", timestamp: "09:35:44 AM", date: "May 24, 2026", eventType: "fullscreen_exit", severity: "warning", description: "Fullscreen mode exited" },
      { id: "e4", timestamp: "09:52:11 AM", date: "May 24, 2026", eventType: "focus_loss", severity: "warning", description: "Application focus lost for 9.3s" },
      { id: "e5", timestamp: "10:14:55 AM", date: "May 24, 2026", eventType: "inactivity_warning", severity: "warning", description: "No input detected for 95 seconds" },
      { id: "e6", timestamp: "10:28:33 AM", date: "May 24, 2026", eventType: "network_interruption", severity: "critical", description: "Network connection dropped for 11s" },
    ],
  },
];
